apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monolith-app
  template:
    metadata:
      labels:
        app: monolith-app
    spec:
      containers:
      - name: monolith-app
        image: monolith-app:latest
        ports:
        - containerPort: 5000
